# Generated by Django 4.2.3 on 2023-07-16 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_post_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default=' ', upload_to='images/'),
            preserve_default=False,
        ),
    ]
